### PR TITLE
Flagging - Working test and fixed table bug

### PR DESCRIPTION
**Pull request by JakeGeiser**
Added working test in ViewPortfolio test.
Removed comments and console.logs from AboutMeView.
Fixed sorting table of portfolios on user side.

### CODE REVIEW

**Review by ajang06 — DISMISSED** [review]
lgtm

**Review by sophiagavrila — CHANGES_REQUESTED** [review]
@JakeGeiser 3 Security Hotspots picked up by Sonar Cloud [listed in this report](https://sonarcloud.io/project/security_hotspots?id=1058-Sophia-Gavrila-Forge_Portfolio-Frontend&pullRequest=25&resolved=false&types=SECURITY_HOTSPOT)

SonarCloud doens't like that `pass` is hardcoded on line `4` & `5` of `TestUserComponent.tsx`

```
export let testAdminUser = {id: 22, name: "Jurgen Holls", password: "pass", admin: true};
export let testGeneralUser = {id: 25, name: "John Doe", password: "pass", admin: false};
```

**Review by sophiagavrila — DISMISSED** [review]
Passes security check due to removed hotspots.  Good to merge

**Review by ajang06 — APPROVED** [review]
good changes

**Review by sophiagavrila — APPROVED** [review]

**Pull request merged**
