### PR TITLE
New json

### PR DESCRIPTION
**Pull request by m-james-butler**
Adds upload JSON functionality to the portfolios overview page, and an option to export the portfolio from portfolio view. Matches MVP stories "Download Entire Portfolio as JSON" and "Upload Entire Portfolio as JSON."

### CODE REVIEW

**Comment by m-james-butler** [comment]
Note: Please do not merge until the equivalent request on the backend is ready.

**Review by sophiagavrila — DISMISSED** [review]
LGTM

**Review by sophiagavrila — DISMISSED** [review]
LGTM! 

Edit: scratch the above, must fix code duplication

**Comment by ddinh** [comment]
Closing in favor of https://github.com/1058-Sophia-Gavrila-Forge/Portfolio-Frontend/pull/19 which has JSON changes without skill matrix changes

**Pull request closed without merging**
