### PR TITLE
Flagging - tests

### PR DESCRIPTION
**Pull request by nopsal**
Added final tests for components and login validation as well as a minor test for flagging view.

### CODE REVIEW

**Comment by FBThornton** [comment]
Duplicate code failure

- [ ] Consolidate `useCookie` into a function outside of the test

**Review by FBThornton — CHANGES_REQUESTED** [review]
Duplicate code issue
- [x]  Consolidate `useCookie` into a function outside of the test

**Review by sophiagavrila — CHANGES_REQUESTED** [review]
@nopsal Resolve the 3 code smells featured [here](https://sonarcloud.io/project/issues?id=1058-Sophia-Gavrila-Forge_Portfolio-Frontend&pullRequest=36&resolved=false&types=CODE_SMELL)

**Comment by nopsal** [comment]
Code smells were fixed, I'm looking into the build fail now

**Review by sophiagavrila — APPROVED** [review]

**Review by FBThornton — APPROVED** [review]

**Pull request merged**
