### PR TITLE
Dev kube - added k8 frontend manifest

### PR DESCRIPTION
**Pull request by davidpearl20**
added k8 manifest for front end, change from previous configuration which was a monolith deployment

### CODE REVIEW

**Review by MDarmawan — DISMISSED** [review]
I've tested the manifest, and I can access the front and backends.

**Review by escalonn — CHANGES_REQUESTED** [review]
this setup is not very maintainable, it's prone to letting the two versions of the files diverge. i don't see the value of doing it this way instead of letting each repo manage its own independent deployment and service, even for an MVP.

**Comment by escalonn** [comment]
also, the PR name isn't descriptive enough

**Comment by davidpearl20** [comment]
Created a frontend only manifest, deleted the monolith manifest.

**Review by escalonn — APPROVED** [review]
ok for mvp. pr title is still not very good and PR description is now just wrong. update the PR description at least before merging.

**Review by SWHarrison — APPROVED** [review]

**Pull request merged**
