### PR TITLE
Finished Functionality SkillMatrix 

### PR DESCRIPTION
**Pull request by andregoulbourne**
Done

- Added components to update and display skill matrices etc.

To Do

-  toast/snack bars, flagging, and static criteria

### CODE REVIEW

**Review by thomaspceci — DISMISSED** [review]
Looks good, Andre!

**Review by Nbot07 — DISMISSED** [review]
looks good

**Comment by sophiagavrila** [comment]
Holding off on merging this until i get the word 

- [x] update branch: pull from `dev` into this before it can be merged

**Review by sophiagavrila — CHANGES_REQUESTED** [review]
@thomaspceci just need to clean up this code smell: Sonar Cloud report  [here](https://sonarcloud.io/project/issues?id=1058-Sophia-Gavrila-Forge_Portfolio-Frontend&pullRequest=28&resolved=false&types=CODE_SMELL)

- [x] remove the import `useEffect` from `SkillMatrixContainer.tsx`

**Review by sophiagavrila — APPROVED** [review]

**Review by m-james-butler — APPROVED** [review]

**Review by sophiagavrila — APPROVED** [review]

**Pull request merged**
